# SPDX-License-Identifier: AGPL-3.0-only
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/LauncherVersion.cmake")
if(DEFINED INVALID_VERSION)
    cuajone_launcher_version("${INVALID_VERSION}" "${TEST_OUTPUT}/invalid.rc")
    return()
endif()
foreach(version IN ITEMS "" "1.2.3.4" "255.255.65535.65535")
    cuajone_launcher_version("${version}" "${TEST_OUTPUT}/test.rc")
    file(READ "${TEST_OUTPUT}/test.rc" resource)
    if("${version}" STREQUAL "")
        set(tuple "0,0,0,0")
        set(identity "0.0.0.0-dev")
        set(flags "VS_FF_PRIVATEBUILD")
    else()
        string(REPLACE "." "," tuple "${version}")
        set(identity "${version}")
        set(flags "0")
    endif()
    foreach(fragment IN ITEMS "FILEVERSION ${tuple}" "PRODUCTVERSION ${tuple}"
            "FILEFLAGS ${flags}" "\"FileVersion\", \"${identity}\\0\"")
        string(FIND "${resource}" "${fragment}" position)
        if(position EQUAL -1)
            message(FATAL_ERROR "Generated resource missing: ${fragment}")
        endif()
    endforeach()
endforeach()
foreach(invalid IN ITEMS "1.2.3" "1.2.3.4.5" "01.2.3.4" "-1.2.3.4"
        "1.2.3.65536" "1.2.9999999999999999999999.4" "1.2.3.4-preview" "1.2.3.4;5")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DINVALID_VERSION=${invalid}"
        "-DTEST_OUTPUT=${TEST_OUTPUT}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(result EQUAL 0)
        message(FATAL_ERROR "Accepted invalid version: ${invalid}")
    endif()
endforeach()
message(STATUS "Version resource generation and rejection tests passed")
