# SPDX-License-Identifier: AGPL-3.0-only

function(cuajone_launcher_version version product_version output)
    if("${version}" STREQUAL "")
        set(CUAJONE_VERSION_NUMBER "0.0.0.0")
        set(CUAJONE_VERSION_IDENTITY "0.0.0.0-dev")
        set(CUAJONE_VERSION_FLAGS "VS_FF_PRIVATEBUILD")
    else()
        if(NOT "${version}" MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
            message(FATAL_ERROR "CUAJONE_FILE_VERSION must be four canonical decimal components")
        endif()
        string(REPLACE "." ";" parts "${version}")
        foreach(part IN LISTS parts)
            string(LENGTH "${part}" length)
            if(length GREATER 5 OR part GREATER 65535)
                message(FATAL_ERROR "CUAJONE_FILE_VERSION components must be in [0, 65535]")
            endif()
        endforeach()
        set(CUAJONE_VERSION_NUMBER "${version}")
        set(CUAJONE_VERSION_IDENTITY "${version}")
        set(CUAJONE_VERSION_FLAGS "0")
    endif()
    if("${product_version}" STREQUAL "")
        set(CUAJONE_PRODUCT_VERSION_VALUE "")
        set(CUAJONE_VERSION_DISPLAY "${CUAJONE_VERSION_IDENTITY}")
    else()
        if("${product_version}" MATCHES "[\"\r\n]")
            message(FATAL_ERROR "CUAJONE_PRODUCT_VERSION cannot contain quotes or newlines")
        endif()
        string(LENGTH "${product_version}" product_version_length)
        if(product_version_length GREATER 255)
            message(FATAL_ERROR "CUAJONE_PRODUCT_VERSION must be at most 255 characters")
        endif()
        set(CUAJONE_PRODUCT_VERSION_VALUE
            "VALUE \"ProductVersion\", \"${product_version}\\0\"")
        set(CUAJONE_VERSION_DISPLAY "${product_version}")
    endif()
    string(REPLACE "." "," CUAJONE_VERSION_TUPLE "${CUAJONE_VERSION_NUMBER}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../resources/launcher_version.rc.in" "${output}" @ONLY)
    set(CUAJONE_VERSION_IDENTITY "${CUAJONE_VERSION_IDENTITY}" PARENT_SCOPE)
    set(CUAJONE_VERSION_DISPLAY "${CUAJONE_VERSION_DISPLAY}" PARENT_SCOPE)
endfunction()
